In [12]:
from dbfread import DBF
import pandas as pd
import requests
import matplotlib.pyplot as plt
import seaborn as sns

file_path = r"C:\Users\noahf\Documents\NSS\Capstone\data\SLD_Trans45.dbf"
table = DBF(file_path, load=True)

slb = pd.DataFrame(iter(table))

In [24]:
censuskey = 'a8775ccd78031cc3c891457933435342a8f711c3'
censuskey

'a8775ccd78031cc3c891457933435342a8f711c3'

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
slb.head()

,GEOID10,CBG_ID,CBSA,CBSA_Name,TrAccess_I,Pop_byTr,Pop_byTr_m,Pop_byTr_1,Pop_byTr_a,Pct_Pop_by,Pct_Pop__1,Pct_Pop__2,Pct_Pop__3,HU_byTr,HH_byTr,Wrks_byTr,Wrks_byTr_,Wrks_byTr1,Wrks_byT_1,Pct_Wrks_b,Pct_Wrks_1,Pct_Wrks_2,Pct_Wrks_3,LoWgWrks_b,LoWgWrks_1,LoWgWrks_2,MeWgWrks_b,HiWgWrks_b,LoMeWgWrks,LoMeWgWr_1,LoMeWgWr_2,Pct_LoWgWr,Pct_LoWg_1,Pct_LoWg_2,Pct_LoWg_3,Pct_MeWgWr,Pct_LoMeWg,Pct_LoMe_1,Pct_LoMe_2,Pct_LoMe_3,Jobs_byTr,Jobs_byTr_,Jobs_byTr1,Job_byTr_A,Pct_Jobs_b,Pct_Jobs_1,Pct_Jobs_2,Pct_Jobs_3,Shape_Leng,Shape_Area
0,010890109021,1.089011e+10,26620.0,"Huntsville, AL",0.00,0,0.0,76219.0,14477.3,0.000000,0.0,0.18252,0.034668,0,0,0,0,27554,5087.08,0.000000,0.005312,0.168816,0.031167,0,203,9067,0,0,0.0,520,21110,0.000000,0.005166,0.230736,0.043455,0.000000,0.000000,0.005375,0.218218,0.040321,0,61667,2573,12930.3,0.000000,0.013858,0.332132,0.069641,0.330973,0.002018
1,010890109022,1.089011e+10,26620.0,"Huntsville, AL",0.00,0,0.0,76219.0,14477.3,0.000000,0.0,0.18252,0.034668,0,0,0,0,27554,5087.08,0.000000,0.005312,0.168816,0.031167,0,203,9067,0,0,0.0,520,21110,0.000000,0.005166,0.230736,0.043455,0.000000,0.000000,0.005375,0.218218,0.040321,0,61667,2573,12930.3,0.000000,0.013858,0.332132,0.069641,0.424572,0.006323
2,010890107022,1.089011e+10,26620.0,"Huntsville, AL",0.00,0,0.0,76219.0,14477.3,0.000000,0.0,0.18252,0.034668,0,0,0,0,27554,5087.08,0.000000,0.005312,0.168816,0.031167,0,203,9067,0,0,0.0,520,21110,0.000000,0.005166,0.230736,0.043455,0.000000,0.000000,0.005375,0.218218,0.040321,0,61667,2573,12930.3,0.000000,0.013858,0.332132,0.069641,0.168004,0.001686
3,010890013012,1.089001e+10,26620.0,"Huntsville, AL",0.32,27090,0.0,76219.0,14477.3,0.064872,0.0,0.18252,0.034668,11769,10616,9662,0,27554,5087.08,0.059196,0.005312,0.168816,0.031167,3262,203,9067,4454,1946,7716.0,520,21110,0.083011,0.005166,0.230736,0.043455,0.077539,0.079762,0.005375,0.218218,0.040321,6830,61667,2573,12930.3,0.036786,0.013858,0.332132,0.069641,0.053789,0.000135
4,010890017002,1.089002e+10,26620.0,"Huntsville, AL",0.00,0,0.0,76219.0,14477.3,0.000000,0.0,0.18252,0.034668,0,0,0,0,27554,5087.08,0.000000,0.005312,0.168816,0.031167,0,203,9067,0,0,0.0,520,21110,0.000000,0.005166,0.230736,0.043455,0.000000,0.000000,0.005375,0.218218,0.040321,0,61667,2573,12930.3,0.000000,0.013858,0.332132,0.069641,0.051042,0.000102

# Cleaning

In [5]:
slb.columns

Index(['GEOID10', 'CBG_ID', 'CBSA', 'CBSA_Name', 'TrAccess_I', 'Pop_byTr',
       'Pop_byTr_m', 'Pop_byTr_1', 'Pop_byTr_a', 'Pct_Pop_by', 'Pct_Pop__1',
       'Pct_Pop__2', 'Pct_Pop__3', 'HU_byTr', 'HH_byTr', 'Wrks_byTr',
       'Wrks_byTr_', 'Wrks_byTr1', 'Wrks_byT_1', 'Pct_Wrks_b', 'Pct_Wrks_1',
       'Pct_Wrks_2', 'Pct_Wrks_3', 'LoWgWrks_b', 'LoWgWrks_1', 'LoWgWrks_2',
       'MeWgWrks_b', 'HiWgWrks_b', 'LoMeWgWrks', 'LoMeWgWr_1', 'LoMeWgWr_2',
       'Pct_LoWgWr', 'Pct_LoWg_1', 'Pct_LoWg_2', 'Pct_LoWg_3', 'Pct_MeWgWr',
       'Pct_LoMeWg', 'Pct_LoMe_1', 'Pct_LoMe_2', 'Pct_LoMe_3', 'Jobs_byTr',
       'Jobs_byTr_', 'Jobs_byTr1', 'Job_byTr_A', 'Pct_Jobs_b', 'Pct_Jobs_1',
       'Pct_Jobs_2', 'Pct_Jobs_3', 'Shape_Leng', 'Shape_Area'],
      dtype='object')

In [6]:
#Getting CBG_ID out of scientific notation
slb['CBG_ID'] = slb['CBG_ID'].astype('int64')

In [7]:
slb_forq3pt1 = slb[['GEOID10', 'CBG_ID', 'CBSA', 'CBSA_Name', 'TrAccess_I', 'Pop_byTr',
       'Pop_byTr_m', 'Pop_byTr_1', 'Pop_byTr_a', 'Pct_Pop_by', 'Pct_Pop__1',
       'Pct_Pop__2', 'Pct_Pop__3', 'HU_byTr', 'HH_byTr', 'Wrks_byTr',
       'Wrks_byTr_', 'Wrks_byTr1', 'Wrks_byT_1', 'Pct_Wrks_b', 'Pct_Wrks_1',
       'Pct_Wrks_2', 'Pct_Wrks_3', 'LoWgWrks_b', 'LoWgWrks_1', 'LoWgWrks_2',
       'MeWgWrks_b', 'HiWgWrks_b', 'LoMeWgWrks', 'LoMeWgWr_1', 'LoMeWgWr_2',
       'Pct_LoWgWr', 'Pct_LoWg_1', 'Pct_LoWg_2', 'Pct_LoWg_3', 'Pct_MeWgWr',
       'Pct_LoMeWg', 'Pct_LoMe_1', 'Pct_LoMe_2', 'Pct_LoMe_3', 'Jobs_byTr',
       'Jobs_byTr_', 'Jobs_byTr1', 'Job_byTr_A', 'Pct_Jobs_b', 'Pct_Jobs_1',
       'Pct_Jobs_2', 'Pct_Jobs_3', 'Shape_Leng', 'Shape_Area']]

# How does access to urban mobility impact economic opportunities & equity?

In [9]:
df.head()

NameError: name 'df' is not defined

In [ ]:
newdf = df.sort_values('Pct_Wrks_b', ascending=False).head(50)

In [ ]:
newdf.columns